2025-03-31 12:32:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-03-31 12:35:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-03-31 12:49:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-03-31 21:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.5.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.5.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.5.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:110)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:106)
	at AxInventoryRestore-3.5.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:96)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
	at java.base/java.lang.Thread.run(Thread.java:1583)
